
services:
  wordpress:
    image: wordpress
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
    - mariadb
    volumes:
    - web_data:/var/www/html
    env_file:
    - .env
    networks:
      inception:
    restart: always
  mariadb:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
    - db_data:/var/lib/mysql
    networks:
      inception:
    restart: always
  nginx:
    image: nginx
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
    - wordpress
    ports:
    - "443:443"
    volumes:
    - web_data:/var/www/html
    networks:
      inception:
    restart: always

networks:
      inception:

volumes:
  web_data:
  db_data: