
services:
  wordpress:
    image: wordpress
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
    - mariadb
    volumes:
    - ./web:/var/www/html
    env_file:
    - .env
    networks:
      inception:
  mariadb:
    image: mariadb
    build: requirements/mariadb/.
    container_name: mariadb
    volumes:
    - ./database:/var/lib/mysql
    networks:
      inception:
  nginx:
    image: nginx
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
    - wordpress
    ports:
    - "443:443"
    volumes:
    - ./web:/var/www/html
    networks:
      inception:

networks:
      inception: